# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/oura-nbdev-dashboard',
                'doc_host': 'https://jotaporras.github.io',
                'git_url': 'https://github.com/jotaporras/oura-nbdev-dashboard',
                'lib_path': 'oura_nbdev_dashboard'},
  'syms': { 'oura_nbdev_dashboard.core': {'oura_nbdev_dashboard.core.foo': ('core.html#foo', 'oura_nbdev_dashboard/core.py')},
            'oura_nbdev_dashboard.total_sleep': { 'oura_nbdev_dashboard.total_sleep.foo': ( 'first_nbdev.html#foo',
                                                                                            'oura_nbdev_dashboard/total_sleep.py'),
                                                  'oura_nbdev_dashboard.total_sleep.say_hello': ( 'first_nbdev.html#say_hello',
                                                                                                  'oura_nbdev_dashboard/total_sleep.py')}}}