# AUTOGENERATED! DO NOT EDIT! File to edit: ../total_sleep_demo.ipynb.

# %% auto 0
__all__ = ['get_daily_sleep']

# %% ../total_sleep_demo.ipynb 1
import json
import requests

def get_daily_sleep(
    start_date: str, # end date
    end_date: str,# start date
    token: str, #Oura's personal access token 
) -> dict: # Returns the data JSOn of the response
    url = 'https://api.ouraring.com/v2/usercollection/sleep' 
    params={ 
        'start_date': start_date, 
        'end_date':end_date 
    }
    headers = { 
      'Authorization': f'Bearer {token}' 
    }
    response = requests.request('GET',url,headers=headers,params=params)
    return json.loads(response.text)['data']
